language: 'node_js'
node_js: '8'

before_script:
- yarn build-storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: storybook-static
  repo: christopherkade/ReactCraft
  target_branch: gh-pages
  on:
    branch: master
